require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IngredientisationsController do

  # This should return the minimal set of attributes required to create a valid
  # Ingredientisation. As you add validations to Ingredientisation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IngredientisationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ingredientisations as @ingredientisations" do
      ingredientisation = Ingredientisation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ingredientisations).should eq([ingredientisation])
    end
  end

  describe "GET show" do
    it "assigns the requested ingredientisation as @ingredientisation" do
      ingredientisation = Ingredientisation.create! valid_attributes
      get :show, {:id => ingredientisation.to_param}, valid_session
      assigns(:ingredientisation).should eq(ingredientisation)
    end
  end

  describe "GET new" do
    it "assigns a new ingredientisation as @ingredientisation" do
      get :new, {}, valid_session
      assigns(:ingredientisation).should be_a_new(Ingredientisation)
    end
  end

  describe "GET edit" do
    it "assigns the requested ingredientisation as @ingredientisation" do
      ingredientisation = Ingredientisation.create! valid_attributes
      get :edit, {:id => ingredientisation.to_param}, valid_session
      assigns(:ingredientisation).should eq(ingredientisation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ingredientisation" do
        expect {
          post :create, {:ingredientisation => valid_attributes}, valid_session
        }.to change(Ingredientisation, :count).by(1)
      end

      it "assigns a newly created ingredientisation as @ingredientisation" do
        post :create, {:ingredientisation => valid_attributes}, valid_session
        assigns(:ingredientisation).should be_a(Ingredientisation)
        assigns(:ingredientisation).should be_persisted
      end

      it "redirects to the created ingredientisation" do
        post :create, {:ingredientisation => valid_attributes}, valid_session
        response.should redirect_to(Ingredientisation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ingredientisation as @ingredientisation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ingredientisation.any_instance.stub(:save).and_return(false)
        post :create, {:ingredientisation => {}}, valid_session
        assigns(:ingredientisation).should be_a_new(Ingredientisation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ingredientisation.any_instance.stub(:save).and_return(false)
        post :create, {:ingredientisation => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ingredientisation" do
        ingredientisation = Ingredientisation.create! valid_attributes
        # Assuming there are no other ingredientisations in the database, this
        # specifies that the Ingredientisation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ingredientisation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => ingredientisation.to_param, :ingredientisation => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested ingredientisation as @ingredientisation" do
        ingredientisation = Ingredientisation.create! valid_attributes
        put :update, {:id => ingredientisation.to_param, :ingredientisation => valid_attributes}, valid_session
        assigns(:ingredientisation).should eq(ingredientisation)
      end

      it "redirects to the ingredientisation" do
        ingredientisation = Ingredientisation.create! valid_attributes
        put :update, {:id => ingredientisation.to_param, :ingredientisation => valid_attributes}, valid_session
        response.should redirect_to(ingredientisation)
      end
    end

    describe "with invalid params" do
      it "assigns the ingredientisation as @ingredientisation" do
        ingredientisation = Ingredientisation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ingredientisation.any_instance.stub(:save).and_return(false)
        put :update, {:id => ingredientisation.to_param, :ingredientisation => {}}, valid_session
        assigns(:ingredientisation).should eq(ingredientisation)
      end

      it "re-renders the 'edit' template" do
        ingredientisation = Ingredientisation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ingredientisation.any_instance.stub(:save).and_return(false)
        put :update, {:id => ingredientisation.to_param, :ingredientisation => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ingredientisation" do
      ingredientisation = Ingredientisation.create! valid_attributes
      expect {
        delete :destroy, {:id => ingredientisation.to_param}, valid_session
      }.to change(Ingredientisation, :count).by(-1)
    end

    it "redirects to the ingredientisations list" do
      ingredientisation = Ingredientisation.create! valid_attributes
      delete :destroy, {:id => ingredientisation.to_param}, valid_session
      response.should redirect_to(ingredientisations_url)
    end
  end

end
